// @flow

export const INPUT_CHANGE : 'COMMAND:INPUT_CHANGE' = 'COMMAND:INPUT_CHANGE';
export const INPUT_SET : 'COMMAND:INPUT_SET' = 'COMMAND:INPUT_SET';
export const INPUT_INSERT : 'COMMAND:INPUT_INSERT' = 'COMMAND:INPUT_INSERT';
export const INPUT_REPLACE : 'COMMAND:INPUT_REPLACE' = 'COMMAND:INPUT_REPLACE';
export const MOVE_CARET : 'COMMAND:MOVE_CARET' = 'COMMAND:MOVE_CARET';
export const SET_CARET : 'COMMAND:SET_CARET' = 'COMMAND:SET_CARET';

export type CommandActionType =
  | typeof INPUT_CHANGE
  | typeof INPUT_SET
  | typeof INPUT_INSERT
  | typeof INPUT_REPLACE
  | typeof MOVE_CARET
  | typeof SET_CARET;
